### ISSUE TITLE
Release on MySQL labs after all approvals are ready

### ISSUE THREAD

**Issue by vjovanov** [graalvm/mysql-mle-demos#1]

**Comment by Allsimon** [comment]
Do you have any update on this ?

**Comment by vjovanov** [comment]
GraalVM has been approved yesterday. MySQL should follow in the next week or two. Still, one never knows how long it might take.

**Comment by santec** [comment]
Please tell legals that they should stop slowing down innovation :)

**Comment by vjovanov** [comment]
I am afraid this would slow down innovation even more ;)

**Comment by ocean390** [comment]
Do you have any update after about a month

**Comment by vjovanov** [comment]
Still stuck at legal. I am personally expecting the release in the next 2-3 weeks, but you know how it goes with estimates that are out of your control.

**Comment by santec** [comment]
It would be nice to know what the problem is, if possible. For example if there is some possible incompatibility between licenses, this could be a useful information for the community.

**Comment by tfrancois** [comment]
Hello there...any update on this progress as of yet for availability for use/lab-demo with MySQL?

**Comment by ocean390** [comment]
one more question, how do mle engine prevent the sandbox not to be bypassed? Can the mle version be used in the multi tenant without other isolation mechanism ?

**Comment by vjovanov** [comment]
Don't lose hope.

**Comment by ocean390** [comment]
Are there any update?

**Comment by vjovanov** [comment]
We are still working on the project. The release date is unknown at this point.

**Comment by federico-razzoli** [comment]
@vjovanov you closed this issue, but the README still says you are waiting for an approval. Does this mean that the approval will never happen?

**Comment by vjovanov** [comment]
If it happens, the date is unknown. I will update the README.
